export default [
  {
    title: 'Panel de Control',
    to: { name: 'root' },
    icon: { icon: 'ri-home-smile-2-line' },
  },
  {
    heading: 'PUNTO DE VENTA (POS)',
  },
  {
    title: 'Salón & Mesas',
    to: { name: 'root' },
    icon: { icon: 'ri-layout-grid-line' },
    roles: ['admin', 'cajero', 'mesero', 'garzon'],
  },
  {
    title: 'Comandas & Pedidos',
    to: { name: 'comandas' },
    icon: { icon: 'ri-restaurant-2-line' },
    roles: ['admin', 'cajero', 'mesero', 'garzon'],
  },
  {
    title: 'Monitor Cocina (KDS)',
    to: { name: 'kds' },
    icon: { icon: 'ri-restaurant-line' },
    badgeContent: 'En Vivo',
    badgeClass: 'bg-warning',
    roles: ['admin', 'cocina', 'barman'],
  },
  {
    title: 'Caja & Turnos',
    to: { name: 'caja' },
    icon: { icon: 'ri-safe-2-line' },
    roles: ['admin', 'cajero'],
  },
  {
    title: 'Clientes & Crédito',
    to: { name: 'clientes' },
    icon: { icon: 'ri-user-star-line' },
    roles: ['admin', 'cajero'],
  },
  {
    heading: 'ADMINISTRACIÓN RESTOTECH',
    roles: ['admin'],
  },
  {
    title: 'Administración POS',
    to: { name: 'admin' },
    icon: { icon: 'ri-settings-4-line' },
    badgeContent: 'Admin',
    badgeClass: 'bg-error',
    roles: ['admin'],
  },
  {
    heading: 'INVENTARIO & PRODUCCIÓN',
    roles: ['admin'],
  },
  {
    title: 'Inventario & Compras',
    to: { name: 'inventario' },
    icon: { icon: 'ri-archive-line' },
    badgeContent: 'Stock',
    badgeClass: 'bg-primary',
    roles: ['admin'],
  },
  {
    heading: 'FACTURACIÓN & VENTAS',
    roles: ['admin', 'cajero'],
  },
  {
    title: 'Facturación Bolivia',
    to: { name: 'facturas' },
    icon: { icon: 'ri-file-shield-line' },
    badgeContent: 'SIAT',
    badgeClass: 'bg-success',
    roles: ['admin', 'cajero'],
  },
  {
    title: 'Reportes & Analítica',
    to: { name: 'reportes' },
    icon: { icon: 'ri-bar-chart-grouped-line' },
    badgeContent: 'BI',
    badgeClass: 'bg-info',
    roles: ['admin'],
  },
  {
    heading: 'SOPORTE RIBERSOFT',
  },
  {
    title: 'WhatsApp: 67369293',
    href: 'https://wa.me/59167369293',
    target: '_blank',
    icon: { icon: 'ri-whatsapp-line' },
  },
]