using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace ControlConsumoLib.FactElectSync;

[DebuggerStepThrough]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public class ServicioFacturacionSincronizacionClient : ClientBase<ServicioFacturacionSincronizacion>, ServicioFacturacionSincronizacion
{
	public ServicioFacturacionSincronizacionClient()
	{
	}

	public ServicioFacturacionSincronizacionClient(string endpointConfigurationName)
		: base(endpointConfigurationName)
	{
	}

	public ServicioFacturacionSincronizacionClient(string endpointConfigurationName, string remoteAddress)
		: base(endpointConfigurationName, remoteAddress)
	{
	}

	public ServicioFacturacionSincronizacionClient(string endpointConfigurationName, EndpointAddress remoteAddress)
		: base(endpointConfigurationName, remoteAddress)
	{
	}

	public ServicioFacturacionSincronizacionClient(Binding binding, EndpointAddress remoteAddress)
		: base(binding, remoteAddress)
	{
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaMotivoAnulacionResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacion(sincronizarParametricaMotivoAnulacion request)
	{
		return base.Channel.sincronizarParametricaMotivoAnulacion(request);
	}

	sincronizarParametricaMotivoAnulacionResponse ServicioFacturacionSincronizacion.sincronizarParametricaMotivoAnulacion(sincronizarParametricaMotivoAnulacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacion
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacion(request);
	}

	public respuestaListaParametricas sincronizarParametricaMotivoAnulacion(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaMotivoAnulacion sincronizarParametricaMotivoAnulacion2 = new sincronizarParametricaMotivoAnulacion();
		sincronizarParametricaMotivoAnulacion2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaMotivoAnulacion(sincronizarParametricaMotivoAnulacion2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaMotivoAnulacionResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacionAsync(sincronizarParametricaMotivoAnulacion request)
	{
		return base.Channel.sincronizarParametricaMotivoAnulacionAsync(request);
	}

	Task<sincronizarParametricaMotivoAnulacionResponse> ServicioFacturacionSincronizacion.sincronizarParametricaMotivoAnulacionAsync(sincronizarParametricaMotivoAnulacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacionAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaMotivoAnulacionAsync(request);
	}

	public Task<sincronizarParametricaMotivoAnulacionResponse> sincronizarParametricaMotivoAnulacionAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaMotivoAnulacion sincronizarParametricaMotivoAnulacion2 = new sincronizarParametricaMotivoAnulacion();
		sincronizarParametricaMotivoAnulacion2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaMotivoAnulacionAsync(sincronizarParametricaMotivoAnulacion2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarActividadesResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividades(sincronizarActividades request)
	{
		return base.Channel.sincronizarActividades(request);
	}

	sincronizarActividadesResponse ServicioFacturacionSincronizacion.sincronizarActividades(sincronizarActividades request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividades
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividades(request);
	}

	public respuestaListaActividades sincronizarActividades(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarActividades sincronizarActividades2 = new sincronizarActividades();
		sincronizarActividades2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarActividades(sincronizarActividades2).RespuestaListaActividades;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarActividadesResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividadesAsync(sincronizarActividades request)
	{
		return base.Channel.sincronizarActividadesAsync(request);
	}

	Task<sincronizarActividadesResponse> ServicioFacturacionSincronizacion.sincronizarActividadesAsync(sincronizarActividades request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividadesAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarActividadesAsync(request);
	}

	public Task<sincronizarActividadesResponse> sincronizarActividadesAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarActividades sincronizarActividades2 = new sincronizarActividades();
		sincronizarActividades2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarActividadesAsync(sincronizarActividades2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarFechaHoraResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHora(sincronizarFechaHora request)
	{
		return base.Channel.sincronizarFechaHora(request);
	}

	sincronizarFechaHoraResponse ServicioFacturacionSincronizacion.sincronizarFechaHora(sincronizarFechaHora request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHora
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHora(request);
	}

	public respuestaFechaHora sincronizarFechaHora(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarFechaHora sincronizarFechaHora2 = new sincronizarFechaHora();
		sincronizarFechaHora2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarFechaHora(sincronizarFechaHora2).RespuestaFechaHora;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarFechaHoraResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHoraAsync(sincronizarFechaHora request)
	{
		return base.Channel.sincronizarFechaHoraAsync(request);
	}

	Task<sincronizarFechaHoraResponse> ServicioFacturacionSincronizacion.sincronizarFechaHoraAsync(sincronizarFechaHora request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHoraAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarFechaHoraAsync(request);
	}

	public Task<sincronizarFechaHoraResponse> sincronizarFechaHoraAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarFechaHora sincronizarFechaHora2 = new sincronizarFechaHora();
		sincronizarFechaHora2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarFechaHoraAsync(sincronizarFechaHora2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarListaLeyendasFacturaResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFactura(sincronizarListaLeyendasFactura request)
	{
		return base.Channel.sincronizarListaLeyendasFactura(request);
	}

	sincronizarListaLeyendasFacturaResponse ServicioFacturacionSincronizacion.sincronizarListaLeyendasFactura(sincronizarListaLeyendasFactura request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFactura
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFactura(request);
	}

	public respuestaListaParametricasLeyendas sincronizarListaLeyendasFactura(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaLeyendasFactura sincronizarListaLeyendasFactura2 = new sincronizarListaLeyendasFactura();
		sincronizarListaLeyendasFactura2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaLeyendasFactura(sincronizarListaLeyendasFactura2).RespuestaListaParametricasLeyendas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarListaLeyendasFacturaResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFacturaAsync(sincronizarListaLeyendasFactura request)
	{
		return base.Channel.sincronizarListaLeyendasFacturaAsync(request);
	}

	Task<sincronizarListaLeyendasFacturaResponse> ServicioFacturacionSincronizacion.sincronizarListaLeyendasFacturaAsync(sincronizarListaLeyendasFactura request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFacturaAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaLeyendasFacturaAsync(request);
	}

	public Task<sincronizarListaLeyendasFacturaResponse> sincronizarListaLeyendasFacturaAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaLeyendasFactura sincronizarListaLeyendasFactura2 = new sincronizarListaLeyendasFactura();
		sincronizarListaLeyendasFactura2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaLeyendasFacturaAsync(sincronizarListaLeyendasFactura2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoHabitacionResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacion(sincronizarParametricaTipoHabitacion request)
	{
		return base.Channel.sincronizarParametricaTipoHabitacion(request);
	}

	sincronizarParametricaTipoHabitacionResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoHabitacion(sincronizarParametricaTipoHabitacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacion
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacion(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoHabitacion(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoHabitacion sincronizarParametricaTipoHabitacion2 = new sincronizarParametricaTipoHabitacion();
		sincronizarParametricaTipoHabitacion2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoHabitacion(sincronizarParametricaTipoHabitacion2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoHabitacionResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacionAsync(sincronizarParametricaTipoHabitacion request)
	{
		return base.Channel.sincronizarParametricaTipoHabitacionAsync(request);
	}

	Task<sincronizarParametricaTipoHabitacionResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoHabitacionAsync(sincronizarParametricaTipoHabitacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacionAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoHabitacionAsync(request);
	}

	public Task<sincronizarParametricaTipoHabitacionResponse> sincronizarParametricaTipoHabitacionAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoHabitacion sincronizarParametricaTipoHabitacion2 = new sincronizarParametricaTipoHabitacion();
		sincronizarParametricaTipoHabitacion2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoHabitacionAsync(sincronizarParametricaTipoHabitacion2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarListaActividadesDocumentoSectorResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSector(sincronizarListaActividadesDocumentoSector request)
	{
		return base.Channel.sincronizarListaActividadesDocumentoSector(request);
	}

	sincronizarListaActividadesDocumentoSectorResponse ServicioFacturacionSincronizacion.sincronizarListaActividadesDocumentoSector(sincronizarListaActividadesDocumentoSector request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSector
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSector(request);
	}

	public respuestaListaActividadesDocumentoSector sincronizarListaActividadesDocumentoSector(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaActividadesDocumentoSector sincronizarListaActividadesDocumentoSector2 = new sincronizarListaActividadesDocumentoSector();
		sincronizarListaActividadesDocumentoSector2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaActividadesDocumentoSector(sincronizarListaActividadesDocumentoSector2).RespuestaListaActividadesDocumentoSector;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarListaActividadesDocumentoSectorResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSectorAsync(sincronizarListaActividadesDocumentoSector request)
	{
		return base.Channel.sincronizarListaActividadesDocumentoSectorAsync(request);
	}

	Task<sincronizarListaActividadesDocumentoSectorResponse> ServicioFacturacionSincronizacion.sincronizarListaActividadesDocumentoSectorAsync(sincronizarListaActividadesDocumentoSector request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSectorAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaActividadesDocumentoSectorAsync(request);
	}

	public Task<sincronizarListaActividadesDocumentoSectorResponse> sincronizarListaActividadesDocumentoSectorAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaActividadesDocumentoSector sincronizarListaActividadesDocumentoSector2 = new sincronizarListaActividadesDocumentoSector();
		sincronizarListaActividadesDocumentoSector2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaActividadesDocumentoSectorAsync(sincronizarListaActividadesDocumentoSector2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoDocumentoIdentidadResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidad(sincronizarParametricaTipoDocumentoIdentidad request)
	{
		return base.Channel.sincronizarParametricaTipoDocumentoIdentidad(request);
	}

	sincronizarParametricaTipoDocumentoIdentidadResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoDocumentoIdentidad(sincronizarParametricaTipoDocumentoIdentidad request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidad
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidad(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoDocumentoIdentidad(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoDocumentoIdentidad sincronizarParametricaTipoDocumentoIdentidad2 = new sincronizarParametricaTipoDocumentoIdentidad();
		sincronizarParametricaTipoDocumentoIdentidad2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoDocumentoIdentidad(sincronizarParametricaTipoDocumentoIdentidad2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoDocumentoIdentidadResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidadAsync(sincronizarParametricaTipoDocumentoIdentidad request)
	{
		return base.Channel.sincronizarParametricaTipoDocumentoIdentidadAsync(request);
	}

	Task<sincronizarParametricaTipoDocumentoIdentidadResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoDocumentoIdentidadAsync(sincronizarParametricaTipoDocumentoIdentidad request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidadAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoIdentidadAsync(request);
	}

	public Task<sincronizarParametricaTipoDocumentoIdentidadResponse> sincronizarParametricaTipoDocumentoIdentidadAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoDocumentoIdentidad sincronizarParametricaTipoDocumentoIdentidad2 = new sincronizarParametricaTipoDocumentoIdentidad();
		sincronizarParametricaTipoDocumentoIdentidad2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoDocumentoIdentidadAsync(sincronizarParametricaTipoDocumentoIdentidad2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaUnidadMedidaResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedida(sincronizarParametricaUnidadMedida request)
	{
		return base.Channel.sincronizarParametricaUnidadMedida(request);
	}

	sincronizarParametricaUnidadMedidaResponse ServicioFacturacionSincronizacion.sincronizarParametricaUnidadMedida(sincronizarParametricaUnidadMedida request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedida
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedida(request);
	}

	public respuestaListaParametricas sincronizarParametricaUnidadMedida(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaUnidadMedida sincronizarParametricaUnidadMedida2 = new sincronizarParametricaUnidadMedida();
		sincronizarParametricaUnidadMedida2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaUnidadMedida(sincronizarParametricaUnidadMedida2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaUnidadMedidaResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedidaAsync(sincronizarParametricaUnidadMedida request)
	{
		return base.Channel.sincronizarParametricaUnidadMedidaAsync(request);
	}

	Task<sincronizarParametricaUnidadMedidaResponse> ServicioFacturacionSincronizacion.sincronizarParametricaUnidadMedidaAsync(sincronizarParametricaUnidadMedida request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedidaAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaUnidadMedidaAsync(request);
	}

	public Task<sincronizarParametricaUnidadMedidaResponse> sincronizarParametricaUnidadMedidaAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaUnidadMedida sincronizarParametricaUnidadMedida2 = new sincronizarParametricaUnidadMedida();
		sincronizarParametricaUnidadMedida2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaUnidadMedidaAsync(sincronizarParametricaUnidadMedida2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoDocumentoSectorResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSector(sincronizarParametricaTipoDocumentoSector request)
	{
		return base.Channel.sincronizarParametricaTipoDocumentoSector(request);
	}

	sincronizarParametricaTipoDocumentoSectorResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoDocumentoSector(sincronizarParametricaTipoDocumentoSector request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSector
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSector(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoDocumentoSector(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoDocumentoSector sincronizarParametricaTipoDocumentoSector2 = new sincronizarParametricaTipoDocumentoSector();
		sincronizarParametricaTipoDocumentoSector2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoDocumentoSector(sincronizarParametricaTipoDocumentoSector2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoDocumentoSectorResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSectorAsync(sincronizarParametricaTipoDocumentoSector request)
	{
		return base.Channel.sincronizarParametricaTipoDocumentoSectorAsync(request);
	}

	Task<sincronizarParametricaTipoDocumentoSectorResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoDocumentoSectorAsync(sincronizarParametricaTipoDocumentoSector request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSectorAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoDocumentoSectorAsync(request);
	}

	public Task<sincronizarParametricaTipoDocumentoSectorResponse> sincronizarParametricaTipoDocumentoSectorAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoDocumentoSector sincronizarParametricaTipoDocumentoSector2 = new sincronizarParametricaTipoDocumentoSector();
		sincronizarParametricaTipoDocumentoSector2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoDocumentoSectorAsync(sincronizarParametricaTipoDocumentoSector2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTiposFacturaResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFactura(sincronizarParametricaTiposFactura request)
	{
		return base.Channel.sincronizarParametricaTiposFactura(request);
	}

	sincronizarParametricaTiposFacturaResponse ServicioFacturacionSincronizacion.sincronizarParametricaTiposFactura(sincronizarParametricaTiposFactura request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFactura
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFactura(request);
	}

	public respuestaListaParametricas sincronizarParametricaTiposFactura(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTiposFactura sincronizarParametricaTiposFactura2 = new sincronizarParametricaTiposFactura();
		sincronizarParametricaTiposFactura2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTiposFactura(sincronizarParametricaTiposFactura2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTiposFacturaResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFacturaAsync(sincronizarParametricaTiposFactura request)
	{
		return base.Channel.sincronizarParametricaTiposFacturaAsync(request);
	}

	Task<sincronizarParametricaTiposFacturaResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTiposFacturaAsync(sincronizarParametricaTiposFactura request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFacturaAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTiposFacturaAsync(request);
	}

	public Task<sincronizarParametricaTiposFacturaResponse> sincronizarParametricaTiposFacturaAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTiposFactura sincronizarParametricaTiposFactura2 = new sincronizarParametricaTiposFactura();
		sincronizarParametricaTiposFactura2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTiposFacturaAsync(sincronizarParametricaTiposFactura2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public verificarComunicacionResponse FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacion(verificarComunicacion request)
	{
		return base.Channel.verificarComunicacion(request);
	}

	verificarComunicacionResponse ServicioFacturacionSincronizacion.verificarComunicacion(verificarComunicacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacion
		return this.FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacion(request);
	}

	public respuestaComunicacion verificarComunicacion()
	{
		verificarComunicacion request = new verificarComunicacion();
		return ((ServicioFacturacionSincronizacion)this).verificarComunicacion(request).@return;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<verificarComunicacionResponse> FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacionAsync(verificarComunicacion request)
	{
		return base.Channel.verificarComunicacionAsync(request);
	}

	Task<verificarComunicacionResponse> ServicioFacturacionSincronizacion.verificarComunicacionAsync(verificarComunicacion request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacionAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_verificarComunicacionAsync(request);
	}

	public Task<verificarComunicacionResponse> verificarComunicacionAsync()
	{
		verificarComunicacion request = new verificarComunicacion();
		return ((ServicioFacturacionSincronizacion)this).verificarComunicacionAsync(request);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarListaMensajesServiciosResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServicios(sincronizarListaMensajesServicios request)
	{
		return base.Channel.sincronizarListaMensajesServicios(request);
	}

	sincronizarListaMensajesServiciosResponse ServicioFacturacionSincronizacion.sincronizarListaMensajesServicios(sincronizarListaMensajesServicios request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServicios
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServicios(request);
	}

	public respuestaListaParametricas sincronizarListaMensajesServicios(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaMensajesServicios sincronizarListaMensajesServicios2 = new sincronizarListaMensajesServicios();
		sincronizarListaMensajesServicios2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaMensajesServicios(sincronizarListaMensajesServicios2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarListaMensajesServiciosResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServiciosAsync(sincronizarListaMensajesServicios request)
	{
		return base.Channel.sincronizarListaMensajesServiciosAsync(request);
	}

	Task<sincronizarListaMensajesServiciosResponse> ServicioFacturacionSincronizacion.sincronizarListaMensajesServiciosAsync(sincronizarListaMensajesServicios request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServiciosAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaMensajesServiciosAsync(request);
	}

	public Task<sincronizarListaMensajesServiciosResponse> sincronizarListaMensajesServiciosAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaMensajesServicios sincronizarListaMensajesServicios2 = new sincronizarListaMensajesServicios();
		sincronizarListaMensajesServicios2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaMensajesServiciosAsync(sincronizarListaMensajesServicios2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoMetodoPagoResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPago(sincronizarParametricaTipoMetodoPago request)
	{
		return base.Channel.sincronizarParametricaTipoMetodoPago(request);
	}

	sincronizarParametricaTipoMetodoPagoResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoMetodoPago(sincronizarParametricaTipoMetodoPago request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPago
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPago(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoMetodoPago(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoMetodoPago sincronizarParametricaTipoMetodoPago2 = new sincronizarParametricaTipoMetodoPago();
		sincronizarParametricaTipoMetodoPago2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoMetodoPago(sincronizarParametricaTipoMetodoPago2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoMetodoPagoResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPagoAsync(sincronizarParametricaTipoMetodoPago request)
	{
		return base.Channel.sincronizarParametricaTipoMetodoPagoAsync(request);
	}

	Task<sincronizarParametricaTipoMetodoPagoResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoMetodoPagoAsync(sincronizarParametricaTipoMetodoPago request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPagoAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMetodoPagoAsync(request);
	}

	public Task<sincronizarParametricaTipoMetodoPagoResponse> sincronizarParametricaTipoMetodoPagoAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoMetodoPago sincronizarParametricaTipoMetodoPago2 = new sincronizarParametricaTipoMetodoPago();
		sincronizarParametricaTipoMetodoPago2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoMetodoPagoAsync(sincronizarParametricaTipoMetodoPago2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaEventosSignificativosResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativos(sincronizarParametricaEventosSignificativos request)
	{
		return base.Channel.sincronizarParametricaEventosSignificativos(request);
	}

	sincronizarParametricaEventosSignificativosResponse ServicioFacturacionSincronizacion.sincronizarParametricaEventosSignificativos(sincronizarParametricaEventosSignificativos request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativos
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativos(request);
	}

	public respuestaListaParametricas sincronizarParametricaEventosSignificativos(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaEventosSignificativos sincronizarParametricaEventosSignificativos2 = new sincronizarParametricaEventosSignificativos();
		sincronizarParametricaEventosSignificativos2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaEventosSignificativos(sincronizarParametricaEventosSignificativos2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaEventosSignificativosResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativosAsync(sincronizarParametricaEventosSignificativos request)
	{
		return base.Channel.sincronizarParametricaEventosSignificativosAsync(request);
	}

	Task<sincronizarParametricaEventosSignificativosResponse> ServicioFacturacionSincronizacion.sincronizarParametricaEventosSignificativosAsync(sincronizarParametricaEventosSignificativos request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativosAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaEventosSignificativosAsync(request);
	}

	public Task<sincronizarParametricaEventosSignificativosResponse> sincronizarParametricaEventosSignificativosAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaEventosSignificativos sincronizarParametricaEventosSignificativos2 = new sincronizarParametricaEventosSignificativos();
		sincronizarParametricaEventosSignificativos2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaEventosSignificativosAsync(sincronizarParametricaEventosSignificativos2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoPuntoVentaResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVenta(sincronizarParametricaTipoPuntoVenta request)
	{
		return base.Channel.sincronizarParametricaTipoPuntoVenta(request);
	}

	sincronizarParametricaTipoPuntoVentaResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoPuntoVenta(sincronizarParametricaTipoPuntoVenta request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVenta
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVenta(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoPuntoVenta(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoPuntoVenta sincronizarParametricaTipoPuntoVenta2 = new sincronizarParametricaTipoPuntoVenta();
		sincronizarParametricaTipoPuntoVenta2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoPuntoVenta(sincronizarParametricaTipoPuntoVenta2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoPuntoVentaResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVentaAsync(sincronizarParametricaTipoPuntoVenta request)
	{
		return base.Channel.sincronizarParametricaTipoPuntoVentaAsync(request);
	}

	Task<sincronizarParametricaTipoPuntoVentaResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoPuntoVentaAsync(sincronizarParametricaTipoPuntoVenta request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVentaAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoPuntoVentaAsync(request);
	}

	public Task<sincronizarParametricaTipoPuntoVentaResponse> sincronizarParametricaTipoPuntoVentaAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoPuntoVenta sincronizarParametricaTipoPuntoVenta2 = new sincronizarParametricaTipoPuntoVenta();
		sincronizarParametricaTipoPuntoVenta2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoPuntoVentaAsync(sincronizarParametricaTipoPuntoVenta2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarListaProductosServiciosResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServicios(sincronizarListaProductosServicios request)
	{
		return base.Channel.sincronizarListaProductosServicios(request);
	}

	sincronizarListaProductosServiciosResponse ServicioFacturacionSincronizacion.sincronizarListaProductosServicios(sincronizarListaProductosServicios request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServicios
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServicios(request);
	}

	public respuestaListaProductos sincronizarListaProductosServicios(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaProductosServicios sincronizarListaProductosServicios2 = new sincronizarListaProductosServicios();
		sincronizarListaProductosServicios2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaProductosServicios(sincronizarListaProductosServicios2).RespuestaListaProductos;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarListaProductosServiciosResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServiciosAsync(sincronizarListaProductosServicios request)
	{
		return base.Channel.sincronizarListaProductosServiciosAsync(request);
	}

	Task<sincronizarListaProductosServiciosResponse> ServicioFacturacionSincronizacion.sincronizarListaProductosServiciosAsync(sincronizarListaProductosServicios request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServiciosAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarListaProductosServiciosAsync(request);
	}

	public Task<sincronizarListaProductosServiciosResponse> sincronizarListaProductosServiciosAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarListaProductosServicios sincronizarListaProductosServicios2 = new sincronizarListaProductosServicios();
		sincronizarListaProductosServicios2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarListaProductosServiciosAsync(sincronizarListaProductosServicios2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoEmisionResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmision(sincronizarParametricaTipoEmision request)
	{
		return base.Channel.sincronizarParametricaTipoEmision(request);
	}

	sincronizarParametricaTipoEmisionResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoEmision(sincronizarParametricaTipoEmision request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmision
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmision(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoEmision(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoEmision sincronizarParametricaTipoEmision2 = new sincronizarParametricaTipoEmision();
		sincronizarParametricaTipoEmision2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoEmision(sincronizarParametricaTipoEmision2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoEmisionResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmisionAsync(sincronizarParametricaTipoEmision request)
	{
		return base.Channel.sincronizarParametricaTipoEmisionAsync(request);
	}

	Task<sincronizarParametricaTipoEmisionResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoEmisionAsync(sincronizarParametricaTipoEmision request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmisionAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoEmisionAsync(request);
	}

	public Task<sincronizarParametricaTipoEmisionResponse> sincronizarParametricaTipoEmisionAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoEmision sincronizarParametricaTipoEmision2 = new sincronizarParametricaTipoEmision();
		sincronizarParametricaTipoEmision2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoEmisionAsync(sincronizarParametricaTipoEmision2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaPaisOrigenResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigen(sincronizarParametricaPaisOrigen request)
	{
		return base.Channel.sincronizarParametricaPaisOrigen(request);
	}

	sincronizarParametricaPaisOrigenResponse ServicioFacturacionSincronizacion.sincronizarParametricaPaisOrigen(sincronizarParametricaPaisOrigen request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigen
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigen(request);
	}

	public respuestaListaParametricas sincronizarParametricaPaisOrigen(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaPaisOrigen sincronizarParametricaPaisOrigen2 = new sincronizarParametricaPaisOrigen();
		sincronizarParametricaPaisOrigen2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaPaisOrigen(sincronizarParametricaPaisOrigen2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaPaisOrigenResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigenAsync(sincronizarParametricaPaisOrigen request)
	{
		return base.Channel.sincronizarParametricaPaisOrigenAsync(request);
	}

	Task<sincronizarParametricaPaisOrigenResponse> ServicioFacturacionSincronizacion.sincronizarParametricaPaisOrigenAsync(sincronizarParametricaPaisOrigen request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigenAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaPaisOrigenAsync(request);
	}

	public Task<sincronizarParametricaPaisOrigenResponse> sincronizarParametricaPaisOrigenAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaPaisOrigen sincronizarParametricaPaisOrigen2 = new sincronizarParametricaPaisOrigen();
		sincronizarParametricaPaisOrigen2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaPaisOrigenAsync(sincronizarParametricaPaisOrigen2);
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public sincronizarParametricaTipoMonedaResponse FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMoneda(sincronizarParametricaTipoMoneda request)
	{
		return base.Channel.sincronizarParametricaTipoMoneda(request);
	}

	sincronizarParametricaTipoMonedaResponse ServicioFacturacionSincronizacion.sincronizarParametricaTipoMoneda(sincronizarParametricaTipoMoneda request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMoneda
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMoneda(request);
	}

	public respuestaListaParametricas sincronizarParametricaTipoMoneda(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoMoneda sincronizarParametricaTipoMoneda2 = new sincronizarParametricaTipoMoneda();
		sincronizarParametricaTipoMoneda2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoMoneda(sincronizarParametricaTipoMoneda2).RespuestaListaParametricas;
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public Task<sincronizarParametricaTipoMonedaResponse> FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMonedaAsync(sincronizarParametricaTipoMoneda request)
	{
		return base.Channel.sincronizarParametricaTipoMonedaAsync(request);
	}

	Task<sincronizarParametricaTipoMonedaResponse> ServicioFacturacionSincronizacion.sincronizarParametricaTipoMonedaAsync(sincronizarParametricaTipoMoneda request)
	{
		//ILSpy generated this explicit interface implementation from .override directive in FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMonedaAsync
		return this.FactElectSync_ServicioFacturacionSincronizacion_sincronizarParametricaTipoMonedaAsync(request);
	}

	public Task<sincronizarParametricaTipoMonedaResponse> sincronizarParametricaTipoMonedaAsync(solicitudSincronizacion SolicitudSincronizacion)
	{
		sincronizarParametricaTipoMoneda sincronizarParametricaTipoMoneda2 = new sincronizarParametricaTipoMoneda();
		sincronizarParametricaTipoMoneda2.SolicitudSincronizacion = SolicitudSincronizacion;
		return ((ServicioFacturacionSincronizacion)this).sincronizarParametricaTipoMonedaAsync(sincronizarParametricaTipoMoneda2);
	}
}
