/**
 * PWA — Service Worker registration.
 *
 * Uses `virtual:pwa-register` from vite-plugin-pwa to register the generated
 * service worker (`sw.js`) in production builds.
 *
 * Strategy: registerType = 'prompt'
 *   - New SW installs but does NOT take control immediately.
 *   - App notifies user and asks them to reload (see useSwUpdate composable).
 *   - This avoids garzones being interrupted mid-comanda by a forced refresh.
 *
 * In development (vite dev): no SW is registered (devOptions.enabled = false).
 * In production build: `dist/sw.js` is generated by workbox.
 */

// `virtual:pwa-register` is resolved by vite-plugin-pwa at build time.
// During dev or if the plugin is not installed, the import resolves to a no-op.
export default function () {
  // Plugin is a no-op in dev (devOptions.enabled = false).
  // In production, vite-plugin-pwa injects the registration script automatically
  // via injectRegister: 'script', so no manual call is needed here.
  // This file exists as the canonical place to extend SW behavior (e.g. prompt).
  if (import.meta.env.DEV)
    return

  // The prompt / update flow is handled by useSwUpdate in App.vue.
  // Nothing to do here — registration is auto-injected by the plugin.
}
