<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>ControlConsumoLib</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="MySql.Data">
      <HintPath>..\..\..\..\MySql.Data.dll</HintPath>
    </Reference>
    <Reference Include="ConfigToptech">
      <HintPath>..\..\..\..\ConfigToptech.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>..\..\..\..\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Numerics" />
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>..\..\..\..\ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="System.Security" />
    <Reference Include="ThoughtWorks.QRCode">
      <HintPath>..\..\..\..\ThoughtWorks.QRCode.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Excel">
      <HintPath>..\..\..\..\Microsoft.Office.Interop.Excel.dll</HintPath>
    </Reference>
    <Reference Include="itext.kernel">
      <HintPath>..\..\..\..\itext.kernel.dll</HintPath>
    </Reference>
    <Reference Include="itext.layout">
      <HintPath>..\..\..\..\itext.layout.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualBasic.PowerPacks.Vs">
      <HintPath>..\..\..\..\Microsoft.VisualBasic.PowerPacks.Vs.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Crc32.NET">
      <HintPath>..\..\..\..\Crc32.NET.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>