<?php

declare(strict_types=1);

namespace App\Infrastructure\Providers;

use App\Application\Auth\Services\AuthResponseMapper;
use App\Application\Auth\Services\BranchAccessGuard;
use App\Application\Auth\Services\OperationalContextBootstrapper;
use App\Application\Auth\Services\TenantAccessGuard;
use App\Application\Auth\UseCases\GetAuthenticatedUserUseCase;
use App\Application\Auth\UseCases\LoginWithPasswordUseCase;
use App\Application\Auth\UseCases\ListLoginContextBranchesUseCase;
use App\Application\Auth\UseCases\ListLoginContextTenantsUseCase;
use App\Application\Auth\UseCases\LoginWithPinUseCase;
use App\Application\Auth\UseCases\LogoutUseCase;
use App\Application\Cash\UseCases\CloseCashSessionUseCase;
use App\Application\Sale\Support\SaleAllocationPresenter;
use App\Application\Sale\UseCases\GetSaleUseCase;
use App\Application\Sale\UseCases\ListSalesUseCase;
use App\Application\Shift\Services\OfficialShiftGuard;
use App\Application\Shift\Services\OperationalShiftScheduleResolver;
use App\Application\Shift\UseCases\EnsureOperationalShiftUseCase;
use App\Application\Shift\Services\OfficialShiftWindowBuilder;
use App\Application\Shift\UseCases\CloseOfficialShiftUseCase;
use App\Application\Shift\UseCases\GetCurrentOfficialShiftUseCase;
use App\Application\Shift\UseCases\GetOfficialShiftSummaryUseCase;
use App\Application\Shift\UseCases\GetOfficialShiftUseCase;
use App\Application\Shift\UseCases\ListOfficialShiftsUseCase;
use App\Application\Shift\UseCases\OpenOfficialShiftUseCase;
use App\Application\ShiftConsole\UseCases\GetCurrentShiftConsoleUseCase;
use App\Application\StaffSettlement\Services\SettlementAccessPolicy;
use App\Application\StaffSettlement\UseCases\GenerateCurrentShiftSettlementsUseCase;
use App\Application\StaffSettlement\UseCases\GetCurrentShiftSettlementsUseCase;
use App\Application\StaffSettlement\UseCases\GetSettlementUseCase;
use App\Application\StaffSettlement\UseCases\ListSettlementHistoryUseCase;
use App\Application\Cash\Services\OpenCashSessionResolver;
use App\Application\Cash\Services\ServiceIncomeCashRecorder;
use App\Application\GirlIncome\Services\GirlStaffValidator;
use App\Application\GirlIncome\UseCases\CreateBraceletUseCase;
use App\Application\Platform\UseCases\GetPlatformDashboardUseCase;
use App\Application\Platform\UseCases\PlatformSetupUseCase;
use App\Application\Plan\Support\TenantPlanUsageCalculator;
use App\Application\Plan\UseCases\CreatePlanUseCase;
use App\Application\Plan\UseCases\DeletePlanUseCase;
use App\Application\Plan\UseCases\DuplicatePlanUseCase;
use App\Application\Plan\UseCases\GetPlanLimitsUseCase;
use App\Application\Plan\UseCases\ListPlansUseCase;
use App\Application\Plan\UseCases\UpdatePlanLimitsUseCase;
use App\Application\Plan\UseCases\UpdatePlanUseCase;
use App\Application\Waiter\Services\WaiterOrderAccessPolicy;
use App\Application\Waiter\UseCases\GetWaiterDashboardUseCase;
use App\Application\Waiter\UseCases\GetWaiterMyTablesUseCase;
use App\Application\Waiter\UseCases\ListWaiterOrdersUseCase;
use App\Application\Waiter\UseCases\OpenWaiterTableUseCase;
use App\Application\Settings\UseCases\CreateCashMovementReasonUseCase;
use App\Application\Settings\UseCases\CreatePaymentMethodUseCase;
use App\Application\Settings\UseCases\CreateRoomTypeUseCase;
use App\Application\Settings\UseCases\CreateServiceAreaUseCase;
use App\Application\Settings\UseCases\CreateServiceTableUseCase;
use App\Application\Audit\UseCases\ListAuditLogsUseCase;
use App\Application\Settings\UseCases\BootstrapBranchOperationalDataUseCase;
use App\Application\Settings\UseCases\GetFirstNightChecklistUseCase;
use App\Shared\Application\Support\AuditLogRecorder;
use App\Application\Settings\UseCases\ListCashMovementReasonsUseCase;
use App\Application\Settings\UseCases\ListPaymentMethodsUseCase;
use App\Application\Settings\UseCases\ListRoomTypesUseCase;
use App\Application\Settings\UseCases\ListServiceAreasUseCase;
use App\Application\Settings\UseCases\ListServiceTablesUseCase;
use App\Application\Settings\UseCases\ListWaiterTableAssignmentsUseCase;
use App\Application\Settings\UseCases\SyncWaiterTableAssignmentsUseCase;
use App\Application\Settings\UseCases\UpdateCashMovementReasonUseCase;
use App\Application\Settings\UseCases\UpdatePaymentMethodUseCase;
use App\Application\Settings\UseCases\UpdateRoomTypeUseCase;
use App\Application\Settings\UseCases\UpdateServiceAreaUseCase;
use App\Application\Settings\UseCases\UpdateServiceTableUseCase;
use App\Application\Room\Services\RoomTypeResolver;
use App\Application\ShowType\UseCases\CreateShowTypeUseCase;
use App\Application\ShowType\UseCases\ListShowTypesUseCase;
use App\Application\ShowType\UseCases\UpdateShowTypeUseCase;
use App\Application\Staff\UseCases\ListOperationalGirlsUseCase;
use App\Application\Staff\UseCases\ListOperationalWaitersUseCase;
use App\Application\Staff\UseCases\QuickCreateGirlUseCase;
use App\Application\Staff\UseCases\QuickCreateWaiterUseCase;
use App\Application\StaffSettlement\UseCases\GetSettlementPendingSourcesUseCase;
use App\Application\Tenant\Support\TenantProvisioner;
use App\Application\Tenant\Support\TenantRoleProvisioner;
use App\Application\Room\UseCases\CreateRoomUseCase;
use App\Application\Room\UseCases\GetRoomUseCase;
use App\Application\Room\UseCases\ListAvailableRoomsUseCase;
use App\Application\Room\UseCases\ListCleaningRoomsUseCase;
use App\Application\Room\UseCases\ListRoomsUseCase;
use App\Application\Room\UseCases\MarkRoomAvailableUseCase;
use App\Application\Room\UseCases\MarkRoomCleanUseCase;
use App\Application\Room\UseCases\MarkRoomMaintenanceUseCase;
use App\Application\Room\UseCases\UpdateRoomUseCase;
use App\Application\GirlIncome\UseCases\CreateRoomServiceUseCase;
use App\Application\GirlIncome\UseCases\CreateShowUseCase;
use App\Application\GirlIncome\UseCases\GetBraceletUseCase;
use App\Application\GirlIncome\UseCases\GetRoomServiceUseCase;
use App\Application\GirlIncome\UseCases\GetShowUseCase;
use App\Application\GirlIncome\UseCases\ListCurrentShiftBraceletsUseCase;
use App\Application\GirlIncome\UseCases\CheckRoomServiceUseCase;
use App\Application\GirlIncome\UseCases\FinishRoomServiceUseCase;
use App\Application\GirlIncome\UseCases\ListActiveRoomServicesUseCase;
use App\Application\GirlIncome\UseCases\ListCurrentShiftRoomServicesUseCase;
use App\Application\GirlIncome\UseCases\ListDueRoomServicesUseCase;
use App\Application\Cleaning\UseCases\GetCleaningShiftEarningsUseCase;
use App\Application\Girl\UseCases\GetGirlShiftEarningsUseCase;
use App\Application\GirlIncome\UseCases\ListRoomControlOverviewUseCase;
use App\Application\Notification\Services\NotificationAccessPolicy;
use App\Application\Notification\UseCases\GetUnreadNotificationCountUseCase;
use App\Application\Notification\UseCases\ListNotificationsUseCase;
use App\Application\Notification\UseCases\MarkAllNotificationsReadUseCase;
use App\Application\Notification\UseCases\MarkNotificationReadUseCase;
use App\Application\RoomService\Services\RoomServiceDueNotifier;
use App\Application\GirlIncome\UseCases\ListCurrentShiftShowsUseCase;
use App\Application\StaffSettlement\UseCases\MarkSettlementPaidUseCase;
use App\Application\SSE\Services\OperationalEventEmitter;
use App\Application\SSE\UseCases\IssueOperationalEventTokenUseCase;
use App\Domain\SSE\Repositories\OperationalEventRepositoryInterface;
use App\Domain\SSE\Repositories\SseTokenRepositoryInterface;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentOperationalEventRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentSseTokenRepository;
use App\Application\Cash\Services\CashSessionFinancialSummaryBuilder;
use App\Application\Cash\UseCases\GetCashSessionAdminUseCase;
use App\Application\Cash\UseCases\GetCashSessionsSummaryAdminUseCase;
use App\Application\Cash\UseCases\GetCashSessionCloseCheckUseCase;
use App\Application\Cash\UseCases\GetCurrentCashSessionUseCase;
use App\Application\Cash\UseCases\ListCashSessionsAdminUseCase;
use App\Application\Cash\UseCases\OpenCashSessionUseCase;
use App\Application\Cash\UseCases\RegisterCashMovementUseCase;
use App\Application\Branch\UseCases\CreateBranchAdminUseCase;
use App\Application\Branch\UseCases\GetBranchAdminUseCase;
use App\Application\Branch\UseCases\UpdateBranchAdminUseCase;
use App\Application\Branch\UseCases\GetCurrentBranchUseCase;
use App\Application\Branch\UseCases\ListAvailableBranchesUseCase;
use App\Application\Branch\UseCases\ListBranchesAdminUseCase;
use App\Application\Tenant\UseCases\CreateTenantAdminUseCase;
use App\Application\Tenant\UseCases\GetTenantAdminUseCase;
use App\Application\Tenant\UseCases\UpdateTenantAdminUseCase;
use App\Application\Tenant\UseCases\GetCurrentTenantUseCase;
use App\Application\Tenant\UseCases\ListTenantsAdminUseCase;
use App\Application\Order\UseCases\AddOrderItemUseCase;
use App\Application\Order\UseCases\AssignOrderItemGirlUseCase;
use App\Application\Order\Services\OrderAccessGuard;
use App\Application\Order\Services\BraceletAllocationValidator;
use App\Application\Order\Services\OrderItemReadinessChecker;
use App\Application\Order\Services\OrderPresentationService;
use App\Application\Product\Support\ProductSettlementNormalizer;
use App\Application\Order\UseCases\CancelOrderItemUseCase;
use App\Application\Order\UseCases\CancelOrderUseCase;
use App\Application\Order\UseCases\CreateOrderUseCase;
use App\Application\Order\UseCases\GetOrderPrecheckUseCase;
use App\Application\Order\UseCases\GetOrderUseCase;
use App\Application\Order\UseCases\ListOrdersUseCase;
use App\Application\Order\UseCases\RemoveOrderItemUseCase;
use App\Application\Order\UseCases\SyncOrderItemAllocationsUseCase;
use App\Application\Order\UseCases\UpdateOrderHeaderUseCase;
use App\Application\Order\UseCases\UpdateOrderItemUseCase;
use App\Application\Product\UseCases\CreateProductCategoryUseCase;
use App\Application\Product\UseCases\GetProductCategoryUseCase;
use App\Application\Product\UseCases\UpdateProductCategoryUseCase;
use App\Application\Product\UseCases\CreateProductPriceUseCase;
use App\Application\Product\UseCases\CreateProductUseCase;
use App\Application\Product\UseCases\QuickCreateProductUseCase;
use App\Application\Product\UseCases\GetProductPricesUseCase;
use App\Application\Product\UseCases\GetPosCatalogUseCase;
use App\Application\Product\UseCases\GetProductsUseCase;
use App\Application\Product\UseCases\ListProductCategoriesUseCase;
use App\Application\Product\UseCases\UpdateProductUseCase;
use App\Application\Role\Support\RoleAdminGuard;
use App\Application\Role\UseCases\CreateTenantRoleUseCase;
use App\Application\Role\UseCases\DeleteTenantRoleUseCase;
use App\Application\Role\UseCases\GetTenantRoleUseCase;
use App\Application\Role\UseCases\ListManageablePermissionsUseCase;
use App\Application\Role\UseCases\ListTenantRolesUseCase;
use App\Application\Role\UseCases\UpdateTenantRolePermissionsUseCase;
use App\Application\Role\UseCases\UpdateTenantRoleUseCase;
use App\Application\User\UseCases\CreateUserAdminUseCase;
use App\Application\User\UseCases\ListUsersAdminUseCase;
use App\Application\Reports\UseCases\GetCashReportUseCase;
use App\Application\Reports\Services\ComboBraceletReportingService;
use App\Application\Reports\UseCases\GetProductReconciliationReportUseCase;
use App\Application\Reports\UseCases\GetRoomsReportUseCase;
use App\Application\Reports\UseCases\GetSalesReportUseCase;
use App\Application\Reports\UseCases\GetServicesReportUseCase;
use App\Application\Reports\UseCases\GetSettlementsReportUseCase;
use App\Application\Reports\UseCases\GetShiftClosureCheckUseCase;
use App\Domain\Auth\Repositories\AuthRepositoryInterface;
use App\Domain\Cash\Repositories\CashSessionRepositoryInterface;
use App\Domain\Reports\Repositories\ReportReadRepositoryInterface;
use App\Domain\Sale\Repositories\SaleRepositoryInterface;
use App\Domain\Branch\Repositories\BranchRepositoryInterface;
use App\Domain\Order\Repositories\OrderItemAllocationRepositoryInterface;
use App\Domain\Order\Repositories\OrderRepositoryInterface;
use App\Domain\Sale\Repositories\SaleItemAllocationRepositoryInterface;
use App\Domain\Product\Repositories\ProductCategoryRepositoryInterface;
use App\Domain\Settings\Repositories\CashMovementReasonRepositoryInterface;
use App\Domain\Settings\Repositories\PaymentMethodRepositoryInterface;
use App\Domain\Settings\Repositories\RoomTypeCatalogRepositoryInterface;
use App\Domain\Settings\Repositories\ServiceAreaRepositoryInterface;
use App\Domain\Settings\Repositories\ServiceTableRepositoryInterface;
use App\Domain\Settings\Repositories\WaiterTableAssignmentRepositoryInterface;
use App\Domain\ShowType\Repositories\ShowTypeRepositoryInterface;
use App\Domain\Product\Repositories\ProductPriceRepositoryInterface;
use App\Domain\Product\Repositories\ProductRepositoryInterface;
use App\Domain\Product\Services\ProductPriceResolver;
use App\Domain\Product\Services\ProductPriceValidator;
use App\Domain\Shift\Repositories\OfficialShiftRepositoryInterface;
use App\Domain\GirlIncome\Repositories\BraceletRepositoryInterface;
use App\Domain\Cleaning\Repositories\CleaningTaskRepositoryInterface;
use App\Domain\GirlIncome\Repositories\RoomServiceRepositoryInterface;
use App\Domain\Room\Repositories\RoomRepositoryInterface;
use App\Domain\Notification\Repositories\NotificationRepositoryInterface;
use App\Domain\GirlIncome\Repositories\ShowRepositoryInterface;
use App\Domain\StaffSettlement\Repositories\StaffSettlementRepositoryInterface;
use App\Domain\Tenant\Repositories\TenantRepositoryInterface;
use App\Domain\User\Repositories\UserRepositoryInterface;
use App\Infrastructure\Auth\JwtAuthRepository;
use App\Infrastructure\Laravel\Http\Context\AuthenticatedStaffContext;
use App\Infrastructure\Laravel\Http\Context\BranchContext;
use App\Infrastructure\Laravel\Http\Context\RequestOperationalContext;
use App\Infrastructure\Laravel\Http\Context\TenantContext;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentCashSessionRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentSaleRepository;
use App\Infrastructure\Services\WaiterCommissionResolver;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentBranchRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentOrderItemAllocationRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentOrderRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentSaleItemAllocationRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentOfficialShiftRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentBraceletRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentCleaningTaskRepository;
use App\Infrastructure\Notification\Channels\DatabaseNotificationChannel;
use App\Infrastructure\Notification\Channels\WhatsAppNotificationChannel;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentNotificationRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentRoomRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentRoomServiceRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentShowRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentStaffSettlementRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentProductCategoryRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentProductPriceRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentCashMovementReasonRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentReportReadRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentPaymentMethodRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentRoomTypeCatalogRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentServiceAreaRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentServiceTableRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentWaiterTableAssignmentRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentShowTypeRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentProductRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentTenantRepository;
use App\Infrastructure\Persistence\Eloquent\Repositories\EloquentUserRepository;
use App\Infrastructure\Presentation\Http\ApiResponsePresenter;
use App\Infrastructure\Presentation\Http\Contracts\ApiResponsePresenterInterface;
use App\Shared\Contracts\AuthenticatedStaffContextInterface;
use App\Shared\Contracts\BranchContextInterface;
use App\Shared\Contracts\TenantContextInterface;
use Illuminate\Support\ServiceProvider;

final class NightPosServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(RequestOperationalContext::class);

        $this->app->singleton(TenantContextInterface::class, TenantContext::class);
        $this->app->singleton(BranchContextInterface::class, BranchContext::class);
        $this->app->singleton(AuthenticatedStaffContextInterface::class, AuthenticatedStaffContext::class);

        $this->app->singleton(ApiResponsePresenterInterface::class, ApiResponsePresenter::class);

        $this->app->singleton(TenantRepositoryInterface::class, EloquentTenantRepository::class);
        $this->app->singleton(BranchRepositoryInterface::class, EloquentBranchRepository::class);
        $this->app->singleton(UserRepositoryInterface::class, EloquentUserRepository::class);
        $this->app->singleton(ProductRepositoryInterface::class, EloquentProductRepository::class);
        $this->app->singleton(ProductPriceRepositoryInterface::class, EloquentProductPriceRepository::class);
        $this->app->singleton(ShowTypeRepositoryInterface::class, EloquentShowTypeRepository::class);
        $this->app->singleton(CashMovementReasonRepositoryInterface::class, EloquentCashMovementReasonRepository::class);
        $this->app->singleton(PaymentMethodRepositoryInterface::class, EloquentPaymentMethodRepository::class);
        $this->app->singleton(ServiceAreaRepositoryInterface::class, EloquentServiceAreaRepository::class);
        $this->app->singleton(ServiceTableRepositoryInterface::class, EloquentServiceTableRepository::class);
        $this->app->singleton(WaiterTableAssignmentRepositoryInterface::class, EloquentWaiterTableAssignmentRepository::class);
        $this->app->singleton(RoomTypeCatalogRepositoryInterface::class, EloquentRoomTypeCatalogRepository::class);
        $this->app->singleton(RoomTypeResolver::class);
        $this->app->singleton(WaiterOrderAccessPolicy::class);
        $this->app->singleton(TenantRoleProvisioner::class);
        $this->app->singleton(ProductCategoryRepositoryInterface::class, EloquentProductCategoryRepository::class);
        $this->app->singleton(OfficialShiftRepositoryInterface::class, EloquentOfficialShiftRepository::class);
        $this->app->singleton(OrderRepositoryInterface::class, EloquentOrderRepository::class);
        $this->app->singleton(OrderItemAllocationRepositoryInterface::class, EloquentOrderItemAllocationRepository::class);
        $this->app->singleton(SaleItemAllocationRepositoryInterface::class, EloquentSaleItemAllocationRepository::class);
        $this->app->singleton(CashSessionRepositoryInterface::class, EloquentCashSessionRepository::class);
        $this->app->singleton(SaleRepositoryInterface::class, EloquentSaleRepository::class);
        $this->app->singleton(StaffSettlementRepositoryInterface::class, EloquentStaffSettlementRepository::class);
        $this->app->singleton(BraceletRepositoryInterface::class, EloquentBraceletRepository::class);
        $this->app->singleton(RoomRepositoryInterface::class, EloquentRoomRepository::class);
        $this->app->singleton(CleaningTaskRepositoryInterface::class, EloquentCleaningTaskRepository::class);
        $this->app->singleton(RoomServiceRepositoryInterface::class, EloquentRoomServiceRepository::class);
        $this->app->singleton(NotificationRepositoryInterface::class, EloquentNotificationRepository::class);
        $this->app->singleton(DatabaseNotificationChannel::class);
        $this->app->singleton(WhatsAppNotificationChannel::class);
        $this->app->singleton(RoomServiceDueNotifier::class);
        $this->app->singleton(ShowRepositoryInterface::class, EloquentShowRepository::class);
        $this->app->singleton(WaiterCommissionResolver::class);
        $this->app->singleton(AuthRepositoryInterface::class, JwtAuthRepository::class);

        $this->app->singleton(ProductPriceValidator::class);
        $this->app->singleton(ProductPriceResolver::class);
        $this->app->singleton(ProductSettlementNormalizer::class);

        $this->app->singleton(TenantAccessGuard::class);
        $this->app->singleton(BranchAccessGuard::class);
        $this->app->singleton(OperationalContextBootstrapper::class);
        $this->app->singleton(AuthResponseMapper::class);
        $this->app->singleton(OfficialShiftWindowBuilder::class);
        $this->app->singleton(OperationalShiftScheduleResolver::class);
        $this->app->singleton(EnsureOperationalShiftUseCase::class);
        $this->app->singleton(OfficialShiftGuard::class);

        $this->app->singleton(LoginWithPinUseCase::class);
        $this->app->singleton(ListLoginContextTenantsUseCase::class);
        $this->app->singleton(ListLoginContextBranchesUseCase::class);
        $this->app->singleton(LoginWithPasswordUseCase::class);
        $this->app->singleton(GetAuthenticatedUserUseCase::class);
        $this->app->singleton(LogoutUseCase::class);

        $this->app->singleton(GetCurrentTenantUseCase::class);
        $this->app->singleton(GetCurrentBranchUseCase::class);
        $this->app->singleton(ListAvailableBranchesUseCase::class);
        $this->app->singleton(TenantProvisioner::class);
        $this->app->singleton(TenantPlanUsageCalculator::class);
        $this->app->singleton(ListTenantsAdminUseCase::class);
        $this->app->singleton(CreateTenantAdminUseCase::class);
        $this->app->singleton(PlatformSetupUseCase::class);
        $this->app->singleton(GetPlatformDashboardUseCase::class);
        $this->app->singleton(ListPlansUseCase::class);
        $this->app->singleton(CreatePlanUseCase::class);
        $this->app->singleton(UpdatePlanUseCase::class);
        $this->app->singleton(DeletePlanUseCase::class);
        $this->app->singleton(GetPlanLimitsUseCase::class);
        $this->app->singleton(UpdatePlanLimitsUseCase::class);
        $this->app->singleton(DuplicatePlanUseCase::class);
        $this->app->singleton(GetTenantAdminUseCase::class);
        $this->app->singleton(UpdateTenantAdminUseCase::class);
        $this->app->singleton(ListBranchesAdminUseCase::class);
        $this->app->singleton(CreateBranchAdminUseCase::class);
        $this->app->singleton(GetBranchAdminUseCase::class);
        $this->app->singleton(UpdateBranchAdminUseCase::class);
        $this->app->singleton(ListUsersAdminUseCase::class);
        $this->app->singleton(CreateUserAdminUseCase::class);
        $this->app->singleton(RoleAdminGuard::class);
        $this->app->singleton(ListTenantRolesUseCase::class);
        $this->app->singleton(ListManageablePermissionsUseCase::class);
        $this->app->singleton(GetTenantRoleUseCase::class);
        $this->app->singleton(CreateTenantRoleUseCase::class);
        $this->app->singleton(UpdateTenantRoleUseCase::class);
        $this->app->singleton(UpdateTenantRolePermissionsUseCase::class);
        $this->app->singleton(DeleteTenantRoleUseCase::class);

        $this->app->singleton(GetProductsUseCase::class);
        $this->app->singleton(GetPosCatalogUseCase::class);
        $this->app->singleton(CreateProductUseCase::class);
        $this->app->singleton(QuickCreateProductUseCase::class);
        $this->app->singleton(UpdateProductUseCase::class);
        $this->app->singleton(GetProductPricesUseCase::class);
        $this->app->singleton(CreateProductPriceUseCase::class);
        $this->app->singleton(ListProductCategoriesUseCase::class);
        $this->app->singleton(CreateProductCategoryUseCase::class);
        $this->app->singleton(GetProductCategoryUseCase::class);
        $this->app->singleton(UpdateProductCategoryUseCase::class);

        $this->app->singleton(ListOrdersUseCase::class);
        $this->app->singleton(CreateOrderUseCase::class);
        $this->app->singleton(ComboBraceletReportingService::class);
        $this->app->singleton(SaleAllocationPresenter::class);
        $this->app->singleton(GetOrderUseCase::class);
        $this->app->singleton(GetOrderPrecheckUseCase::class);
        $this->app->singleton(AddOrderItemUseCase::class);
        $this->app->singleton(AssignOrderItemGirlUseCase::class);
        $this->app->singleton(SendOrderToBarUseCase::class);
        $this->app->singleton(CancelOrderUseCase::class);
        $this->app->singleton(OrderAccessGuard::class);
        $this->app->singleton(OrderItemPricing::class);
        $this->app->singleton(BraceletAllocationValidator::class);
        $this->app->singleton(OrderItemReadinessChecker::class);
        $this->app->singleton(OrderPresentationService::class);
        $this->app->singleton(UpdateOrderItemUseCase::class);
        $this->app->singleton(SyncOrderItemAllocationsUseCase::class);
        $this->app->singleton(RemoveOrderItemUseCase::class);
        $this->app->singleton(CancelOrderItemUseCase::class);
        $this->app->singleton(UpdateOrderHeaderUseCase::class);

        $this->app->singleton(CashSessionFinancialSummaryBuilder::class);
        $this->app->singleton(GetCurrentCashSessionUseCase::class);
        $this->app->singleton(GetCashSessionCloseCheckUseCase::class);
        $this->app->singleton(ListCashSessionsAdminUseCase::class);
        $this->app->singleton(GetCashSessionAdminUseCase::class);
        $this->app->singleton(GetCashSessionsSummaryAdminUseCase::class);
        $this->app->singleton(OpenCashSessionUseCase::class);
        $this->app->singleton(RegisterCashMovementUseCase::class);
        $this->app->singleton(CloseCashSessionUseCase::class);

        $this->app->singleton(ChargeOrderUseCase::class);
        $this->app->singleton(ListSalesUseCase::class);
        $this->app->singleton(GetSaleUseCase::class);

        $this->app->singleton(GetCurrentShiftConsoleUseCase::class);
        $this->app->singleton(GetCurrentOfficialShiftUseCase::class);
        $this->app->singleton(OpenOfficialShiftUseCase::class);
        $this->app->singleton(CloseOfficialShiftUseCase::class);
        $this->app->singleton(ListOfficialShiftsUseCase::class);
        $this->app->singleton(GetOfficialShiftUseCase::class);
        $this->app->singleton(GetOfficialShiftSummaryUseCase::class);

        $this->app->singleton(SettlementAccessPolicy::class);
        $this->app->singleton(GenerateCurrentShiftSettlementsUseCase::class);
        $this->app->singleton(GetCurrentShiftSettlementsUseCase::class);
        $this->app->singleton(GetSettlementUseCase::class);
        $this->app->singleton(MarkSettlementPaidUseCase::class);
        $this->app->singleton(ListSettlementHistoryUseCase::class);
        $this->app->singleton(GetSettlementPendingSourcesUseCase::class);

        $this->app->singleton(GirlStaffValidator::class);
        $this->app->singleton(OpenCashSessionResolver::class);
        $this->app->singleton(ServiceIncomeCashRecorder::class);
        $this->app->singleton(ListCurrentShiftBraceletsUseCase::class);
        $this->app->singleton(CreateBraceletUseCase::class);
        $this->app->singleton(GetBraceletUseCase::class);
        $this->app->singleton(ListCurrentShiftRoomServicesUseCase::class);
        $this->app->singleton(ListActiveRoomServicesUseCase::class);
        $this->app->singleton(ListDueRoomServicesUseCase::class);
        $this->app->singleton(ListRoomControlOverviewUseCase::class);
        $this->app->singleton(ListOperationalGirlsUseCase::class);
        $this->app->singleton(QuickCreateGirlUseCase::class);
        $this->app->singleton(ListOperationalWaitersUseCase::class);
        $this->app->singleton(QuickCreateWaiterUseCase::class);
        $this->app->singleton(ListShowTypesUseCase::class);
        $this->app->singleton(CreateShowTypeUseCase::class);
        $this->app->singleton(UpdateShowTypeUseCase::class);
        $this->app->singleton(ListCashMovementReasonsUseCase::class);
        $this->app->singleton(CreateCashMovementReasonUseCase::class);
        $this->app->singleton(UpdateCashMovementReasonUseCase::class);
        $this->app->singleton(ListPaymentMethodsUseCase::class);
        $this->app->singleton(CreatePaymentMethodUseCase::class);
        $this->app->singleton(UpdatePaymentMethodUseCase::class);
        $this->app->singleton(ListServiceAreasUseCase::class);
        $this->app->singleton(CreateServiceAreaUseCase::class);
        $this->app->singleton(UpdateServiceAreaUseCase::class);
        $this->app->singleton(ListServiceTablesUseCase::class);
        $this->app->singleton(CreateServiceTableUseCase::class);
        $this->app->singleton(UpdateServiceTableUseCase::class);
        $this->app->singleton(ListWaiterTableAssignmentsUseCase::class);
        $this->app->singleton(SyncWaiterTableAssignmentsUseCase::class);
        $this->app->singleton(ListRoomTypesUseCase::class);
        $this->app->singleton(CreateRoomTypeUseCase::class);
        $this->app->singleton(UpdateRoomTypeUseCase::class);
        $this->app->singleton(GetFirstNightChecklistUseCase::class);
        $this->app->singleton(BootstrapBranchOperationalDataUseCase::class);
        $this->app->singleton(ListAuditLogsUseCase::class);
        $this->app->bind(AuditLogRecorder::class);
        $this->app->singleton(GetWaiterDashboardUseCase::class);
        $this->app->singleton(ListWaiterOrdersUseCase::class);
        $this->app->singleton(GetWaiterMyTablesUseCase::class);
        $this->app->singleton(OpenWaiterTableUseCase::class);
        $this->app->singleton(ListRoomsUseCase::class);
        $this->app->singleton(ListAvailableRoomsUseCase::class);
        $this->app->singleton(ListCleaningRoomsUseCase::class);
        $this->app->singleton(GetRoomUseCase::class);
        $this->app->singleton(CreateRoomUseCase::class);
        $this->app->singleton(UpdateRoomUseCase::class);
        $this->app->singleton(MarkRoomCleanUseCase::class);
        $this->app->singleton(GetCleaningShiftEarningsUseCase::class);
        $this->app->singleton(GetGirlShiftEarningsUseCase::class);
        $this->app->singleton(MarkRoomMaintenanceUseCase::class);
        $this->app->singleton(MarkRoomAvailableUseCase::class);
        $this->app->singleton(CreateRoomServiceUseCase::class);
        $this->app->singleton(GetRoomServiceUseCase::class);
        $this->app->singleton(FinishRoomServiceUseCase::class);
        $this->app->singleton(CheckRoomServiceUseCase::class);
        $this->app->singleton(NotificationAccessPolicy::class);
        $this->app->singleton(ListNotificationsUseCase::class);
        $this->app->singleton(GetUnreadNotificationCountUseCase::class);
        $this->app->singleton(MarkNotificationReadUseCase::class);
        $this->app->singleton(MarkAllNotificationsReadUseCase::class);
        $this->app->singleton(ListCurrentShiftShowsUseCase::class);
        $this->app->singleton(CreateShowUseCase::class);
        $this->app->singleton(GetShowUseCase::class);

        // SSE infrastructure
        $this->app->singleton(OperationalEventRepositoryInterface::class, EloquentOperationalEventRepository::class);
        $this->app->singleton(SseTokenRepositoryInterface::class, EloquentSseTokenRepository::class);
        $this->app->singleton(ReportReadRepositoryInterface::class, EloquentReportReadRepository::class);
        $this->app->singleton(GetDailyReportUseCase::class);
        $this->app->singleton(GetSalesReportUseCase::class);
        $this->app->singleton(GetCashReportUseCase::class);
        $this->app->singleton(GetServicesReportUseCase::class);
        $this->app->singleton(GetSettlementsReportUseCase::class);
        $this->app->singleton(GetRoomsReportUseCase::class);
        $this->app->singleton(GetShiftClosureCheckUseCase::class);
        $this->app->singleton(GetProductReconciliationReportUseCase::class);
        $this->app->singleton(OperationalEventEmitter::class);
        $this->app->singleton(IssueOperationalEventTokenUseCase::class);
    }

    public function boot(): void
    {
        //
    }
}
